### ISSUE TITLE
Lightweight Version

### ISSUE THREAD

**Issue by narayanlongani** [zd11024/NaviLLM#17]
Does it have a lightweight version?
Or is it possible to run this real time using edge devices like Jetson nano with RGB-D camera or other sensors?

**Comment by zd11024** [comment]
Sry, we previously tried to adopt `opt-3b`  as the backbone, but we did not store the corresponding weights. For your question, I believe that with specific optimization such as quantization, we could run this in real time at a relatively low speed, especially since there are many powerful and lightweight LLMs ( such as Phi-3-mini, LLaMA3-8B) recently. But this requires a lot of engineering optimiziations.
